FROM node:16.17.0-bullseye

WORKDIR /app/server

COPY server/package.json server/package-lock.json ./
RUN npm ci

COPY server/ ./
RUN npx tsc --pretty false

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "dist/index.js"]
