-- 在已导入 variety_shop.sql 的本机库上追加 S9/P2 表结构（可重复执行需自行判断列是否已存在）
USE variety_shop;

ALTER TABLE users ADD COLUMN points_balance INT NOT NULL DEFAULT 0;
ALTER TABLE goods
  ADD COLUMN special_price_cent INT NULL,
  ADD COLUMN special_start DATETIME NULL,
  ADD COLUMN special_end DATETIME NULL;
ALTER TABLE orders
  ADD COLUMN user_coupon_id BIGINT NULL,
  ADD COLUMN coupon_discount_cent INT NOT NULL DEFAULT 0,
  ADD COLUMN points_used INT NOT NULL DEFAULT 0,
  ADD COLUMN points_discount_cent INT NOT NULL DEFAULT 0,
  ADD COLUMN activity_type VARCHAR(16) NOT NULL DEFAULT 'NORMAL',
  ADD COLUMN activity_id BIGINT NULL,
  ADD COLUMN team_id BIGINT NULL;

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(40) NOT NULL,
  type VARCHAR(16) NOT NULL,
  min_amount_cent INT NOT NULL DEFAULT 0,
  reduce_cent INT NOT NULL DEFAULT 0,
  discount_bp INT NOT NULL DEFAULT 10000,
  discount_cap_cent INT NULL,
  per_user_limit INT NOT NULL DEFAULT 1,
  total_limit INT NULL,
  claimed_count INT NOT NULL DEFAULT 0,
  start_at DATETIME NOT NULL,
  end_at DATETIME NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_coupons (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  coupon_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'UNUSED',
  claimed_at DATETIME NOT NULL,
  used_at DATETIME NULL,
  order_id BIGINT UNSIGNED NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_user_status (user_id, status)
);

CREATE TABLE IF NOT EXISTS points_ledger (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  delta INT NOT NULL,
  balance_after INT NOT NULL,
  reason VARCHAR(32) NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  note VARCHAR(80) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_user_id (user_id, id)
);

CREATE TABLE IF NOT EXISTS group_buy_activities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  goods_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(40) NOT NULL,
  required_count INT NOT NULL DEFAULT 2,
  group_price_cent INT NOT NULL,
  expire_hours INT NOT NULL DEFAULT 24,
  per_user_limit INT NOT NULL DEFAULT 1,
  start_at DATETIME NOT NULL,
  end_at DATETIME NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_buy_teams (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  activity_id BIGINT UNSIGNED NOT NULL,
  leader_user_id BIGINT UNSIGNED NOT NULL,
  status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
  expire_at DATETIME NOT NULL,
  success_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS group_buy_members (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  team_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  order_id BIGINT UNSIGNED NOT NULL,
  joined_at DATETIME NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_team_user (team_id, user_id)
);

CREATE TABLE IF NOT EXISTS seckill_activities (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  goods_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(40) NOT NULL,
  seckill_price_cent INT NOT NULL,
  seckill_stock INT NOT NULL,
  per_user_limit INT NOT NULL DEFAULT 1,
  start_at DATETIME NOT NULL,
  end_at DATETIME NOT NULL,
  enabled TINYINT NOT NULL DEFAULT 1,
  deleted_at DATETIME NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_subscribes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  scene VARCHAR(32) NOT NULL,
  accepted TINYINT NOT NULL DEFAULT 0,
  template_id VARCHAR(64) NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_scene (user_id, scene)
);

CREATE TABLE IF NOT EXISTS notify_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  scene VARCHAR(32) NOT NULL,
  order_id BIGINT UNSIGNED NULL,
  title VARCHAR(80) NOT NULL,
  body VARCHAR(200) NULL,
  status VARCHAR(16) NOT NULL,
  channel VARCHAR(16) NOT NULL DEFAULT 'SUBSCRIBE',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
